// <auto-generated />
using System;
using DatchikiSharp.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DatchikiSharp.Core.Migrations
{
    [DbContext(typeof(ScanerContext))]
    partial class ScanerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("DatchikiSharp.Core.Entitites.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Number")
                        .HasColumnType("longtext");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("DatchikiSharp.Core.Entitites.Scaner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Desc")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Scaners");
                });

            modelBuilder.Entity("DatchikiSharp.Core.Events.RoomEvent", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("RoomId1")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime(6)");

                    b.HasKey("RoomId");

                    b.HasIndex("RoomId1");

                    b.ToTable("RoomEvents");
                });

            modelBuilder.Entity("DatchikiSharp.Core.Events.SecurityEvent", b =>
                {
                    b.Property<int>("ScanerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.Property<int>("ScanerId1")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ScanerId");

                    b.HasIndex("ScanerId1");

                    b.ToTable("SecurityEvents");
                });

            modelBuilder.Entity("DatchikiSharp.Core.Events.RoomEvent", b =>
                {
                    b.HasOne("DatchikiSharp.Core.Entitites.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("DatchikiSharp.Core.Events.SecurityEvent", b =>
                {
                    b.HasOne("DatchikiSharp.Core.Entitites.Scaner", "Scaner")
                        .WithMany()
                        .HasForeignKey("ScanerId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scaner");
                });
#pragma warning restore 612, 618
        }
    }
}
